# Generated by Django 5.0.7 on 2024-07-17 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_affidavit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affidavit',
        ),
    ]
