# Generated by Django 5.0.7 on 2024-07-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_affidavit'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('in_revision', 'In Revision'), ('complete', 'Complete')], default='active', max_length=20),
        ),
    ]
