# Generated by Django 5.0.7 on 2024-07-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_affidavit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='affidavit',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='affidavit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('in_review', 'In Review'), ('in_revision', 'In Revision'), ('complete', 'Complete')], default='active', max_length=20),
        ),
    ]
