# Generated by Django 5.0.7 on 2024-07-31 19:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_profile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affidavit',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
