# Generated by Django 5.0.7 on 2024-07-16 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_agent_profile_auctioneer_profile_caretaker_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('review', 'Review'), ('in_revision', 'In Revision'), ('complete', 'Complete')], default='active', max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.profile')),
            ],
        ),
    ]
