# Generated by Django 5.0.7 on 2024-07-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_affidavit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Affidavit',
        ),
    ]
